services:
  service-discovery:
    build:
      dockerfile: ./Dockerfile
      target: runtime
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: xxx
      AWS_REGION: eu-west-1

      SCRAPER_0_CLUSTER_ARN: "arn:aws:rds:eu-west-1:xxx:cluster:c0"
      SCRAPER_1_CLUSTER_ARN: "arn:aws:rds:eu-west-1:xxx:cluster:c1"
      SCRAPER_2_CLUSTER_ARN: "arn:aws:rds:us-east-1:xxx:cluster:admin"
